/**
 * GF(2^8) Galois field arithmetic, shared by the Reed-Solomon and BCH codecs.
 *
 * Field: GF(2^8) generated by the primitive polynomial
 *   x^8 + x^4 + x^3 + x^2 + 1  (0x11d), with generator element alpha = 2.
 *
 * EXP[i] = alpha^i,  LOG[x] = discrete log of x base alpha.
 * The EXP table is doubled (length 512) so that multiplication can index
 * LOG[a] + LOG[b] (max 508) without a modulo.
 */

export const PRIMITIVE = 0x11d;
export const FIELD_SIZE = 256;
export const ORDER = 255; // number of nonzero elements = 2^8 - 1

export const EXP = new Uint8Array(512);
export const LOG = new Uint8Array(256);

(function initTables() {
    let x = 1;
    for (let i = 0; i < ORDER; i++) {
        EXP[i] = x;
        LOG[x] = i;
        x <<= 1;
        if (x & 0x100) x ^= PRIMITIVE;
    }
    // Duplicate so EXP[i + ORDER] == EXP[i]; lets us avoid % when adding logs.
    for (let i = ORDER; i < 512; i++) EXP[i] = EXP[i - ORDER];
})();

export function gfMul(a: number, b: number): number {
    if (a === 0 || b === 0) return 0;
    return EXP[LOG[a] + LOG[b]];
}

export function gfDiv(a: number, b: number): number {
    if (b === 0) throw new Error('GF(256) division by zero');
    if (a === 0) return 0;
    return EXP[LOG[a] + ORDER - LOG[b]];
}

export function gfInv(a: number): number {
    if (a === 0) throw new Error('GF(256) inverse of zero');
    return EXP[ORDER - LOG[a]];
}

/** alpha^n, i.e. the field element whose discrete log is n (mod 255). */
export function gfAlphaPow(n: number): number {
    return EXP[((n % ORDER) + ORDER) % ORDER];
}

/** a^n for an arbitrary field element a. */
export function gfPow(a: number, n: number): number {
    if (a === 0) return n === 0 ? 1 : 0;
    return EXP[(LOG[a] * n) % ORDER];
}

/* ------------------------------------------------------------------ *
 * Polynomials with coefficients in GF(2^8).
 * Convention (used by the BCH codec): index = degree, so poly[0] is the
 * constant term. Reed-Solomon uses its own leading-coefficient-first
 * convention internally and does not use these helpers.
 * ------------------------------------------------------------------ */

/** Multiply two polynomials (degree-indexed) over GF(2^8). */
export function polyMul(a: number[], b: number[]): number[] {
    const res = new Array(a.length + b.length - 1).fill(0);
    for (let i = 0; i < a.length; i++) {
        if (a[i] === 0) continue;
        for (let j = 0; j < b.length; j++) {
            res[i + j] ^= gfMul(a[i], b[j]);
        }
    }
    return res;
}

/** Evaluate a degree-indexed polynomial at x (Horner). */
export function polyEval(poly: number[], x: number): number {
    let y = 0;
    for (let d = poly.length - 1; d >= 0; d--) {
        y = gfMul(y, x) ^ poly[d];
    }
    return y;
}
